export function renderUserMd(params: { name?: string }) {
  return `# USER\n\nName: ${params.name ?? "(unknown)"}\n\n## Preferences\n- PRs only\n- Draft external comms\n`;
}

export function renderGoalsMd() {
  return `# GOALS\n\n- (add your goals here)\n`;
}

export function renderMemoryMd() {
  return `# MEMORY\n\n(autogenerated seed)\n`;
}
