export function renderUserMd(params: { name?: string; timezone?: string | null }) {
  return `# USER\n\nName: ${params.name ?? "(unknown)"}\nTimezone: ${params.timezone ?? "(unknown)"}\n\n## Preferences\n- Draft external comms\n- PRs only\n`;
}

export function renderGoalsMd(params?: { goals?: string[] }) {
  const goals = params?.goals?.length ? params.goals : ["(add your goals here)"];
  return `# GOALS\n\n${goals.map((g) => `- ${g}`).join("\n")}\n`;
}

export function renderMemoryMd(params?: { seed?: string | null }) {
  return `# MEMORY\n\n${params?.seed ? params.seed : "(autogenerated seed)"}\n`;
}

export function renderStartHereMd(params?: {
  rootDir?: string;
  cloudOptional?: boolean;
}) {
  const root = params?.rootDir || "~/.myo";
  return `# Start Here — Myo × OpenClaw (Local-First)\n\nThis folder is your local Mission Control. You can use it **without** a Myo.ai account.\n\n## 1) What this is\n- **Projects/** = goals + context\n- **TASKS.md** = your execution queue (local-first)\n- **JOBS.md** = scheduled automations (OpenClaw cron)\n\n## 2) Quick start (no account)\n1. Open and edit: \`${root}/GOALS.md\`\n2. Create a project folder under \`${root}/projects/\`\n3. Optional: add local cron jobs via \`openclaw cron add\` (then use \`openclaw cron list\` to verify).\n\n## 3) Optional: connect Myo.ai (sync)\nIf you later want cross-device sync + vault/search, connect:\n\n\`\`\`bash\nopenclaw myo connect --api-key <key>\nopenclaw myo sync\n\`\`\`\n\n## 4) Common commands\n\`\`\`bash\nopenclaw myo init\nopenclaw myo status\nopenclaw myo sync\nopenclaw myo push\nopenclaw myo jobs:import\n\`\`\`\n`;
}

export function renderJobsStarterMd(params?: { timezone?: string }) {
  const tz = params?.timezone || "America/Los_Angeles";
  return `# JOBS\n\n> Editable format (plugin parses):\n> - [x] <cron> (<timezone>) (id:<uuid>)\n\n## Starter examples (copy/paste, then replace id with a real uuid if you plan to sync)\n- [ ] 0 8 * * * (${tz}) (id:example-morning-brief)\n- [ ] 0 14 * * * (${tz}) (id:example-afternoon-intel)\n- [ ] 0 19 * * * (${tz}) (id:example-fitness-check)\n\nNotes:\n- These are placeholders until you connect to Myo.ai or import real jobs.\n- For real jobs, run: \`openclaw cron list --json\` and/or \`openclaw myo jobs:import\`.\n`;
}

export function slugify(input: string) {
  return (input || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 64) || "project";
}

export function renderProjectMd(p: any) {
  return `# PROJECT\n\nName: ${p.name || "(unnamed)"}\nStatus: ${p.status || "active"}\n\n## Goal\n${p.goal_title || ""}\n\n${p.goal_description || ""}\n`;
}

export function renderTasksMd(params: { tasks: any[] }) {
  const tasks = params.tasks || [];
  const byStatus = (s: string) => tasks.filter((t) => t.status === s);

  const renderLine = (t: any) => {
    const checked = String(t.status || "").toLowerCase() === "done";
    return `- [${checked ? "x" : " "}] ${t.title || "(untitled)"}  (id:${t.id})`;
  };

  const section = (title: string, items: any[]) => {
    if (!items.length) return `## ${title}\n\n- (none)\n`;
    return `## ${title}\n\n${items.map(renderLine).join("\n")}\n`;
  };

  return [
    "# TASKS\n",
    section("Blocked", byStatus("blocked")),
    section("Needs Review", byStatus("review")),
    section("In Progress", byStatus("in_progress")),
    section("Queued", byStatus("queued")),
    section("Backlog", byStatus("pending")),
    section("Done", byStatus("done")),
  ].join("\n");
}

export function renderJobsMd(params: { jobs: any[] }) {
  const jobs = params.jobs || [];
  // Editable format (plugin parses):
  // - [x] 0 8 * * * (America/Los_Angeles) (id:uuid)
  // - [ ] 0 14 * * * (UTC) (id:uuid)
  if (!jobs.length) return "# JOBS\n\n- (none)\n";
  return (
    "# JOBS\n\n" +
    jobs
      .map((j) => {
        const enabled = !!j.enabled;
        const cron = j.cron_expression || "";
        const tz = j.timezone || "UTC";
        return `- [${enabled ? "x" : " "}] ${cron} (${tz}) (id:${j.id})`;
      })
      .join("\n") +
    "\n"
  );
}

export function renderSessionsMd(params: { sessions: any[] }) {
  const sessions = params.sessions || [];
  if (!sessions.length) return "# SESSIONS\n\n- (none)\n";

  const line = (s: any) => {
    const title = s.title || s.key || "(untitled)";
    const channel = s.channel ? ` • ${s.channel}` : "";
    const agent = s.agent ? ` • ${s.agent}` : "";
    const last = s.last_message_at ? ` • last: ${new Date(s.last_message_at).toLocaleString()}` : "";
    return `- ${title}${channel}${agent}${last}  (key:${s.key})`;
  };

  return `# SESSIONS\n\n${sessions.map(line).join("\n")}\n`;
}
